config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#home"
  get "/help",        to: "static_pages#help"
  get "/about",       to: "static_pages#about"
  get "/contact",     to: "static_pages#contact"

  get    "/login",    to: "sessions#new"
  post   "/login",    to: "sessions#create"
  delete "/logout",   to: "sessions#destroy"

  get "/signup",      to: "users#new"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes

  def hello
    render html: "hello world"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session

      user.remember_token = SecureRandom.urlsafe_base64
      if ActiveModel::SecurePassword.min_cost
        cost = BCrypt::Engine::MIN_COST
      else
        cost = BCrypt::Engine.cost
      end
      digest_string = BCrypt::Password.create(user.remember_token, cost: cost)
      user.update_attribute(:remember_digest, digest_string)

      cookies.permanent.encrypted[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token

      if params[:session][:remember_me] == "1"
        user.remember_token = SecureRandom.urlsafe_base64
        if ActiveModel::SecurePassword.min_cost
          cost = BCrypt::Engine::MIN_COST
        else
          cost = BCrypt::Engine.cost
        end
        user.update_attribute(:remember_digest, BCrypt::Password.create(user.remember_token, cost: cost))
      else
        user.update_attribute(:remember_digest, nil)
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
      end

      session[:user_id] = user.id
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find_by(id: session[:user_id])
    if @user
      @user.update_attribute(:remember_digest, nil)
    end
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
    reset_session
    @current_user = nil
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action -> {
    if (user_id = session[:user_id])
      if @current_user.nil?
        @current_user = User.find_by(id: user_id)
      elsif (user_id = cookies.encrypted[:user_id])
        user = User.find_by(id: user_id)
        if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
          sessions[:user_id] = user.id
          @current_user = user
        end
      end
    end
    unless !@current_user.nil?
      flash[:danger] = "Please log in"
      redirect_to login_url, status: :see_other
    end
  }, only: [ :edit, :update ]
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      reset_session
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:name, :email, :password, :password_confirmation))
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render "edit", status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
        by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About",   about_path    %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="https://news.railsltutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>
            

app/views/layouts/_header.html.erb
<%
    # current_user
    if session[:user_id]
        if @current_user.nil?
            @current_user = User.find_by(id: session[:user_id])
        end
    elsif cookies.encrypted[:user_id]
        raise
        user = User.find_by(id: cookies.encrypted[:user_id])
        if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
            session[:user_id] = user.id
            @current_user = user
        end
    end

%>
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",     root_path   %></li>
            <li><%= link_to "Help",     help_path   %></li>
            <% if !@current_user.nil? %>
                <li><%= link_to "Users", '#' %></li>
                <li class="dropdown">
                    <a href="#" id="account" class="dropdown-toggle">
                        Account <b class="caret"></b>
                    </a>
                    <ul id="dropdown-menu" class="dropdown-menu">
                        <li><%= link_to "Profile", @current_user %></li>
                        <li><%= link_to "Settings", edit_user_path(@current_user) %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "Log out", logout_path,
                                                data: { "turbo-method": :delete } %>
                        </li>
                    </ul>
                </li>
            <% else %>    
                <li><%= link_to "Log in", login_path %></li>
            <% end %>
        </ul>
    </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag  "application", "data-turbo-track": "reload"%>
<%= javascript_importmap_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <%= render 'layouts/rails_default'%>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    is a <a href="https://railstutorial.jp/#ebook">book</a> and
    <a href="https://railstutorial.jp/screencast">screencast</a>
    to teach web development with
    <a href="https://rubyonrails.org/">Ruby on Rails</a>.
    This is the sample app for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "contact") %>
<p>contact</p>
<p>
    Contact the Ruby on Rails Tutorial about the sample app at the
    <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help
  page</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em> 
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the 
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application
  </h2>

  <%= link_to "Singn up now", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), "https://rubyonrails.org/"%>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages' %>
    
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form_control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form_control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form_control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form_control' %>

    <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render "form" %>
        <div class="gravatar_edit">
            <%= image_tag("https://secure.grabatar.com/avatar/#{Digest::MD5::hexdigest(@user.email.downcase)}", alt: @user.name, class: "gravatar") %>
            <a href="https://gravatar.com/emails" target="_blank">change</a>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render "form" %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= image_tag("https://secure.gravatar.com/avatar/#{Digest::MD5::hexdigest(@user.email.downcase)}", alt: @user.name, class: "gravatar") %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>